[package]
name = "kani-poc-contract"
version = "0.1.0"
edition = "2021"

[dependencies]
soroban-sdk = "20.5.0"

[dev-dependencies]
soroban-sdk = { version = "20.5.0", features = ["testutils"] }

[features]
testutils = ["soroban-sdk/testutils"]



[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(kani)"] }

[lib]
crate-type = ["cdylib", "rlib"]
