[workspace]
members = [
    "tooling/sanctifier-cli",
    "tooling/sanctifier-core",
    "contracts/vulnerable-contract",
]
resolver = "2"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
